// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
	"strings"
)

// FuncSignature describes arguments and return type for Go/Plan9 translation.
type FuncSignature struct {
	Name       string
	GoName     string
	ParamCount int // number of 64-bit word parameters
	HasReturn  bool
}

// EmitPlan9Assembly formats disassembled functions into a complete Plan 9 .s file.
func EmitPlan9Assembly(pkg string, syms []Symbol, sigs map[string]FuncSignature) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by c2plan9. DO NOT EDIT.\n\n")
	buf.WriteString("//go:build amd64 && !purego\n\n")
	buf.WriteString("#include \"textflag.h\"\n\n")

	for _, sym := range syms {
		if sym.IsLocal || len(sym.Code) == 0 {
			continue
		}

		insts, err := DisassembleAMD64(sym.Code, sym.Offset)
		if err != nil {
			return nil, fmt.Errorf("failed to disassemble symbol %s: %w", sym.Name, err)
		}

		sig, hasSig := sigs[sym.Name]
		goName := sym.Name
		if hasSig && sig.GoName != "" {
			goName = sig.GoName
		}

		// Calculate frame and argument stack size
		paramCount := 6
		hasRet := true
		if hasSig {
			paramCount = sig.ParamCount
			hasRet = sig.HasReturn
		}

		argSize := paramCount * 8
		if hasRet {
			argSize += 8
		}

		// Emit TEXT declaration
		fmt.Fprintf(&buf, "// func %s\n", goName)
		fmt.Fprintf(&buf, "TEXT ·%s(SB), NOSPLIT, $0-%d\n", goName, argSize)

		// Emit Argument Loading Prologue (System V ABI register mapping)
		regNames := []string{"DI", "SI", "DX", "CX", "R8", "R9"}
		for i := 0; i < paramCount && i < len(regNames); i++ {
			fmt.Fprintf(&buf, "\tMOVQ arg%d+%d(FP), %s\n", i, i*8, regNames[i])
		}

		if paramCount > 0 {
			buf.WriteString("\n")
		}

		// Emit Disassembled Instructions
		retOffset := paramCount * 8
		for _, inst := range insts {
			if inst.Label != "" {
				fmt.Fprintf(&buf, "%s:\n", inst.Label)
			}

			if inst.IsRet || strings.HasPrefix(inst.Text, "RET") || inst.Text == "LRET" {
				if hasRet {
					fmt.Fprintf(&buf, "\tMOVQ AX, ret+%d(FP)\n", retOffset)
				}
				buf.WriteString("\tRET\n")
			} else {
				fmt.Fprintf(&buf, "\t%s\n", inst.Text)
			}
		}

		hasTrailingRet := len(insts) > 0 && insts[len(insts)-1].IsRet
		if !hasTrailingRet {
			if hasRet {
				fmt.Fprintf(&buf, "\tMOVQ AX, ret+%d(FP)\n", retOffset)
			}
			buf.WriteString("\tRET\n")
		}

		buf.WriteString("\n")
	}

	return buf.Bytes(), nil
}

// EmitGoStub generates companion Go stub declarations.
func EmitGoStub(pkg string, sigs []FuncSignature) []byte {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by c2plan9. DO NOT EDIT.\n\n")
	buf.WriteString("//go:build amd64 && !purego\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import \"unsafe\"\n\n")
	buf.WriteString("var _ = unsafe.Pointer(nil)\n\n")

	for _, sig := range sigs {
		name := sig.GoName
		if name == "" {
			name = sig.Name
		}

		var params []string
		for i := 0; i < sig.ParamCount; i++ {
			params = append(params, fmt.Sprintf("arg%d uint64", i))
		}

		ret := ""
		if sig.HasReturn {
			ret = " uint64"
		}

		buf.WriteString("//go:noescape\n")
		fmt.Fprintf(&buf, "func %s(%s)%s\n\n", name, strings.Join(params, ", "), ret)
	}

	return buf.Bytes()
}
