version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lemon4ksan/foundation)

    gofumpt:
      module-path: github.com/lemon4ksan/foundation
      extra:
        group-params: true

    goimports:
      local-prefixes:
        - github.com/lemon4ksan/foundation

    golines:
      max-len: 120

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - bodyclose
    - nilerr
    - noctx
    - errorlint
    - protogetter
    - gocritic
    - prealloc
    - perfsprint
    - gosec

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters: [errcheck, revive, staticcheck, protogetter]
        path: .*(pb\.go|generated\.go)

      - linters: [gosec]
        text: "G103:"

      - linters: [gosec]
        text: "G104:"

      - linters: [gosec]
        text: "G404:"

      - linters: [gosec]
        text: "G115:"

      - linters: [gosec]
        text: "G306:|G301:"

      - linters: [revive]
        path: "_test\\.go"
        text: "exported: (exported|comment on exported)"

      - linters: [gosec, noctx, bodyclose, errcheck, prealloc, staticcheck, errorlint, gocritic, unused, perfsprint, ineffassign]
        path: "_test\\.go"

      - linters: [gosec]
        text: "G703:|G706:"
        path: "(cmd|scripts)/.*"

    paths:
      - "text/encoding/(charmap|htmlindex|japanese|korean|simplifiedchinese|traditionalchinese|unicode|transform)/.*"
      - "text/transform/.*"
      - "net/hpack/.*"
      - "net/proxy/socks/.*"
      - "net/psl/.*"
      - "codec/compress/(brotli|flate|fse|gzip|huff0|lzma|zstd)/.*"
      - "silicon/simd/fastscan_archsimd\\.go"
