// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func find_match_length_avx2
TEXT ·find_match_length_avx2(SB), NOSPLIT, $0-56
	MOVQ arg0+0(FP), DI
	MOVQ arg1+8(FP), SI
	MOVQ arg2+16(FP), DX
	MOVQ arg3+24(FP), CX
	MOVQ arg4+32(FP), R8
	MOVQ arg5+40(FP), R9

	XORL AX, AX
	NOP
L_0010:
	LEAQ 0x20(AX), CX
	CMPQ CX, DX
	JA L_0043
	VMOVDQU 0(DI)(AX*1), Y0
	VPCMPEQB 0(SI)(AX*1), Y0, Y0
	VPMOVMSKB Y0, R8
	MOVQ CX, AX
	CMPL R8, $-0x1
	JE L_0010
	NOTL R8
	TZCNTL R8, AX
	ADDQ CX, AX
	ADDQ $-0x20, AX
L_003f:
	VZEROUPPER
	MOVQ AX, ret+48(FP)
	RET
L_0043:
	CMPQ AX, DX
	JAE L_003f
	NOP
L_0050:
	MOVBLZX 0(DI)(AX*1), CX
	CMPB CL, 0(SI)(AX*1)
	JNE L_003f
	INCQ AX
	CMPQ DX, AX
	JNE L_0050
	MOVQ DX, AX
	VZEROUPPER
	MOVQ AX, ret+48(FP)
	RET

