// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

package hex

import "unsafe"

var _ = unsafe.Pointer(nil)

//go:noescape
func hex_encode_avx2(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64

//go:noescape
func hex_decode_avx2(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64
