// Code generated by c2plan9. DO NOT EDIT.

//go:build amd64 && !purego

package json

import "unsafe"

var _ = unsafe.Pointer(nil)

//go:noescape
func json_skip_whitespace_avx2(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64

//go:noescape
func json_scan_string_avx2(arg0 uint64, arg1 uint64, arg2 uint64, arg3 uint64, arg4 uint64, arg5 uint64) uint64
